### ISSUE TITLE
docs suggestions

### ISSUE THREAD

**Issue by dragonyanglong** [st3107/pdfstream#2]
In thehttps://st3107.github.io/pdfstream/installation.html

1.`PDFgetX3` not `PDFgetX`.

1. I recommend specify python version when creating the conda convironment. maybe py3 preferred?

1. In the usage doc, why need double two `-`?
`pdfstream -- --help`

**Comment by st3107** [comment]
Thank you for the suggestion.

1. The software works for python >= 3.6 and will be updated to be compatible with the latest python. I wrote this in the conda recipe. When you run conda install, the latest python will be automatically installed if there is no python and if there is a python, conda will check if it is OK. If not, it will tell you what version is required. thus, we don't need to specify python version here.

2. I use the python-fire to initiate the CLI. This module is different from the python built-in module of argument parsing. It follows a different syntax. It treats very input following the command as a flag if there is a "--" before it. Thus, if there is no "--", the software consider that you are inputing a flag called "help" instread of trying to open the help menu.
